services:
  db:
    image: postgres:16
    container_name: supportdb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: supportdb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d supportdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build: .
    container_name: support-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      # IMPORTANT: 'db' is the hostname inside docker network
      DATABASE_URL: postgresql+psycopg2://postgres:pass@db:5432/supportdb
      GROQ_API_KEY: ${GROQ_API_KEY}
    ports:
      - "8000:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

volumes:
  pgdata:
